#       Copyright 2017 IBM Corp All Rights Reserved

#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at

#       http://www.apache.org/licenses/LICENSE-2.0

#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.


################################################################################################
## Configuration for deploying Stock Quote microservice using WebSphere Liberty helm chart
################################################################################################

image:
  repository: ibmstocktrader/stock-quote  # Docker Hub
  #repository: mycluster.icp:8500/stock-trader/stock-quote        # IBM Cloud Private
  #repository: registry.ng.bluemix.net/stock_trader/stock-quote   # IBM Container Service
  tag: latest
  pullPolicy: Always
  extraEnvs:
    - name: REDIS_URL
      valueFrom:
        secretKeyRef:
          name: redis
          key: url
    - name: JWT_AUDIENCE
      valueFrom:
        secretKeyRef:
          name: jwt 
          key: audience
    - name: JWT_ISSUER
      valueFrom:
        secretKeyRef:
          name: jwt
          key: issuer
    - name: STOCKQUOTE_URL
      valueFrom:
        secretKeyRef:
          name: stockquote
          key: url
          optional: true

resourceNameOverride: stock-trader

pod:
  labels:
    solution: stock-trader

service:
  enabled: true
  name: stock-quote-service
  port: 9080
  targetPort: 9080
  type: NodePort
  extraPorts:
    - name: stock-quote-service-https
      protocol: TCP
      port: 9443
      targetPort: 9443

ingress:
  enabled: true 
  path: "/stock-quote/.*"
  annotations: 
    kubernetes.io/ingress.class: "istio"

monitoring:
  enabled: true